### ISSUE TITLE
Minified :(

### ISSUE THREAD

**Issue by ngyikp** [nfriedly/facebook-js-sdk#4]
Starting from df160968cc5ff851880ee8abe8b873136e864eb3, even the 'debug' version of the JS SDK is minified, making direct diffing (and browser console logs...) less useful

Maybe use Prettier to format the code?

**Comment by nfriedly** [comment]
Ok, I added prettier to the script, ran it once locally and checked that in, and then pushed the update to heroku. I think that'll do the trick, but we'll have to wait for the next facebook change to be sure. If it doesn't seem to be working, please re-open this ticket.
