### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by Daniel15** [nfriedly/facebook-js-sdk#5]
Looks like this repo has stopped updating?

**Comment by nfriedly** [comment]
Sorry, I missed this. Looks like facebook got rid of https://connect.facebook.net/en_US/debug.js, so I'll have to figure out which script file makes the most sense to follow.

**Comment by Daniel15** [comment]
From https://developers.facebook.com/docs/javascript/advanced-setup/ it sounds like the URL changed to https://connect.facebook.net/en_US/sdk/debug.js

**Comment by nfriedly** [comment]
Okay, cool. I'm on my phone right now, do you want to send me a PR to fix
it?

Thanks,
-Nathan

**Comment by nfriedly** [comment]
Never mind, I fixed it.

I also found that I can't log into heroku anymore. So I switched it to use GitHub actions.
